apiVersion: v1
kind: Configuration
metadata:
  name: db2wh using LinBit Storage and Pacemaker for HA
  clusterName: db2whcluster
spec:
  db2:
    required:
      role: optimized # optimized or sandbox
      replicated: true # true or false
      databaseName: BLUDB
      instancePort: 50000
      instanceName: db2wh
      instanceID: 3000 # user id for the instance user when we create the user
      instanceGD: 3000 # group id for instance user when we create the group
      fencedID: 4000 # user id for the fenced user when we create the user
      fencedGD: 4000 # group id for fenced user when we create the group
      instanceSecret: cGFzc3dvcmQ= # replace with your base64 encoded password, echo -n 'password' | base64 
      fencedName: db2fenc1
      fencedSecret: cGFzc3dvcmQ= # replace with your base64 encoded password, echo -n 'password' | base64 
      db2Version: 11.5.4.0 # Replace with your name
      db2Binary: v11.5.4_linuxx64_server.tar.gz # Db2 binary that you get from IBM using try and buy
      db2License: db2adv_vpc.lic # The db2 license file.
      numInstances: 1
      numdb: 1
      organization: column
    # optional: - optional fields can be over-written if included in this file
    #   topLevelDir: /db2db
  nodes:
    required:
      numNodes: 4 #Example: 4, 8, 12 16 etc.
      nvmeList: [[{name: /dev/xvdc, size: 25GB}, {name: /dev/xvde, size: 25GB}, {name: /dev/xvdf, size: 25GB}, {name: /dev/xvdg, size: 25GB}], [{name: /dev/xvdc, size: 25GB}, {name: /dev/xvde, size: 25GB}, {name: /dev/xvdf, size: 25GB}, {name: /dev/xvdg, size: 25GB}], [{name: /dev/xvdc, size: 25GB}, {name: /dev/xvde, size: 25GB}, {name: /dev/xvdf, size: 25GB}, {name: /dev/xvdg, size: 25GB}], [{name: /dev/xvdc, size: 25GB}, {name: /dev/xvde, size: 25GB}, {name: /dev/xvdf, size: 25GB}, {name: /dev/xvdg, size: 25GB}]] # GB or TB only
      ipAddresses: [10.11.1.134, 10.11.1.135, 10.11.1.242, 10.11.2.20] #Example: [10.xx.xx.xx, 10.xx.xx.xx, ...]
      names: [p01.zinox.com, p02.zinox.com, p03.zinox.com, p04.zinox.com] #Example: [e1n1, e2n1, ...]
      partitions: 24
  nfs:
    server:
      required: 
        nfsVirtualIP: 10.11.1.2
        cidrNetmask: 20
        nic: eth0
    # optional fields
      # optional:
      #   primitiveName: mynfsserver
      #   nfsPath: /mnt/nfs/nfsserver
    # client:
    #   optional: