apiVersion: v1
kind: Configuration
metadata:
  name: db2 pacemaker corosync configuration
  clusterName: db2whcluster
spec:
  db2:
    required:
      role:
      replicated:
      databaseName:
      instancePort:
      instanceName:
      instanceID:
      instanceGD:
      fencedID:
      fencedGD:
      instanceSecret:
      fencedName:
      fencedSecret:
      db2Version:
      db2Binary:
      db2License:
      numInstances:
      numdb:
      organization:
    optional:
      topLevelDir: /db2db
  nodes:
    required:
      numNodes:  
      nvmeList: 
      ipAddresses: 
      names: 
      partitions: 
    optional:
      dbPrimitiveNamePrefix: NODE
  linbit:
    optional:
      numStripes: 
      stripeSize: 4M
      volumeDefinition:
        nodes:
          size: 
        nfs:
          size: 
          numNFSServers: 4
        db2local:
          size: 
  nfs:
    server:
      required: 
        nfsVirtualIP: 
        cidrNetmask: 
        nic: 
      optional:
        nfsPath: /mnt/nfs/nfsserver
        primitiveName: nfsserver
        virtualIPResourceName: virtip
        exportResourceName: exportfs
        exportResourceDirectory: /mnt/nfs
        mountpointName: nfsfs 
        pacemakerOrderName1: o_exportfs_before_virtip
        pacemakerOrderName2: o_nfsserver_before_exportfs
        pacemakerOrderName3: o_nfsfs_before_nfsserver
        colocationName1: c_virtip_with_exportfs
        colocationName2: c_exportfs_with_nfsserver
        colocationName3: c_nfsserver_with_nfsfs
    client:
      optional:
        mountPoint: /misc/nfsshare
        primitiveName: nfsclient
        cloneName: cl_nfsclient
        orderName: o_exportfs_before_cl_nfsclient

    
      